### ISSUE TITLE
APK Config

### ISSUE THREAD

**Issue by LiamKenyon** [plestoon/tbs-android#2]
Wondering where needs edited to make the APK point to the web url?

Only had a scan through source code but nowhere jumped out.

**Comment by plestoon** [comment]
The app doesn't have any reference to the web url.

The web url is dynamic based on the device ip, even though the port is always 1212.

The web interface is for the users to use their computers to open and set things up

**Comment by LiamKenyon** [comment]
Apologies were meant to close this down as realised when I'd compiled the app haha.
